version: '3.8'

services:
  airflow:
    image: apache/airflow:2.8.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:///opt/airflow/airflow.db
      - AIRFLOW__WEBSERVER__RBAC=True
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./dbt:/opt/airflow/dbt
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: >
      bash -c "pip install --no-cache-dir dbt-core dbt-duckdb pandas faker streamlit duckdb &&\
      airflow db init &&\
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&\
      airflow webserver &\
      airflow scheduler"

  streamlit:
    image: python:3.11-slim
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8501:8501"
    command: >
      bash -c "pip install --no-cache-dir -r requirements.txt &&\
      streamlit run app/streamlit_app.py --server.port 8501 --server.address 0.0.0.0"
